const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],writes=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});let state={enabled:true,known:true,active:false,status:'idle',position:0},mode='paper',slowReads=false,rejectEpoch=false,loseResponse=false,resolvePending=false;const packet={con_id:7,generation:'test',security_type:'STK',currency:'USD',symbol:'QQQ',interval:5,session:'rth',bid:100,ask:101,price_rules:[{low:0,increment:.01}],bars:Array.from({length:70},(_,i)=>({time:1790947800+i*300,open:100,high:102,low:98,close:101}))};
await page.route('**/api/**',async route=>{const req=route.request(),url=new URL(req.url());if(slowReads&&req.method()==='GET'&&url.pathname.includes('/paper-chart/'))await new Promise(r=>setTimeout(r,5000));let result={};if(req.method()==='POST'){const body=req.postDataJSON();writes.push(body);if(rejectEpoch){await route.fulfill({status:409,json:{error:'Account connection changed. Refresh and verify the account before continuing.'}});return;}if(loseResponse){await route.abort('failed');return;}assert.equal(req.headers()['x-wheel-account-epoch'],'test-epoch');if(body.action==='submit'){if(body.tp!=null)assert.ok((body.tp-body.entry)*body.side>0);if(body.sl!=null)assert.ok((body.entry-body.sl)*body.side>0);state={...state,active:true,entry:body.entry,side:body.side,entry_type:'LMT',tif:body.tif,allowed_tifs:['DAY','GTC','OVERNIGHT'],entry_editable:true,order_ref:'ref',edit_snapshot:[{order_id:1,filled:0}],orders:[{role:'entry',quantity:body.quantity,price:body.entry,status:'Submitted'}],status:'working'};}else if(body.cancel){state={enabled:true,known:true,active:false,status:'canceled',position:0};}else if(body.action==='edit_entry'){state={...state,entry:body.price||state.entry,tif:body.tif||state.tif};}result={status:'acknowledged',state};}else if(url.pathname.endsWith('/profiles'))result={selected:mode,verified:true,epoch:'test-epoch'};else if((url.pathname.includes('/stock-chart/')||url.pathname.includes('/stock-chart-latest/')))result={...packet,server_time:Date.now()/1000,interval:Number(url.searchParams.get('interval')),session:url.searchParams.get('session')};else if(url.pathname.includes('/paper-chart/'))result=url.searchParams.has('request_id')?{confirmed:resolvePending,status:resolvePending?'reconciled':'unknown'}:state;else if(url.pathname.endsWith('/pending-orders'))result={orders:state.active?[{symbol:'QQQ',chart_con_id:7,action:'BUY',quantity:1,premium:state.entry,status:'Submitted',tif:state.tif}]:[]};else if(url.pathname.endsWith('/bootstrap'))result={positions:[]};else if(url.pathname.endsWith('/chart-contracts'))result={contracts:[{con_id:7,local_symbol:'QQQ'}]};await route.fulfill({json:result});});
await page.goto('http://127.0.0.1:8765/superchart?con_id=7');await page.waitForFunction(()=>document.getElementById('order-status').textContent.includes('Trading'));await page.waitForFunction(()=>document.getElementById('market-status').textContent.includes('Snapshot')); 
assert.equal(await page.locator('#bracket-enabled').isChecked(),false);
await page.locator('#bracket-enabled').check();assert.equal(await page.locator('#tp-enabled').isChecked(),true);
await page.locator('#tp').fill('0.7');await page.locator('#tp').dispatchEvent('change');
await page.locator('#sl-enabled').uncheck();await page.locator('#bracket-enabled').uncheck();assert.equal(await page.locator('#tp').inputValue(),'0.7');assert.equal(await page.locator('#tp').isDisabled(),true);
await page.locator('#bracket-enabled').check();assert.equal(await page.locator('#tp').inputValue(),'0.7');assert.equal(await page.locator('#sl-enabled').isChecked(),false);
await page.reload();await page.waitForFunction(()=>document.getElementById('order-status').textContent.includes('Trading'));await page.waitForFunction(()=>document.getElementById('market-status').textContent.includes('Snapshot')); assert.equal(await page.locator('#bracket-enabled').isChecked(),true);assert.equal(await page.locator('#sl-enabled').isChecked(),false);
await page.locator('#tp-enabled').uncheck();assert.equal(await page.locator('#bracket-enabled').isChecked(),false);
for(const type of ['OPT','FUT']){packet.security_type=type;await page.reload();await page.waitForFunction(()=>document.getElementById('order-status').textContent.includes('Trading'));await page.waitForFunction(()=>document.getElementById('market-status').textContent.includes('Snapshot')); assert.equal(await page.locator('#bracket-enabled').isChecked(),type==='FUT');}
for(const width of [1440,393]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
assert.equal(writes.length,0);
await page.setViewportSize({width:1440,height:1000});await page.locator('#bracket-enabled').uncheck();await page.locator('#preview').click();await page.frameLocator('#chart').locator('#order-direction').click();await page.waitForFunction(()=>document.getElementById('orders').textContent.includes('Submitted'));assert.equal(writes.length,1);assert.equal(writes[0].tp,undefined);assert.equal(writes[0].sl,undefined);assert.equal(await page.locator('#bracket-control').isVisible(),false);
assert.deepEqual(errors,[]);console.log('Bracket defaults, retention, single leg, persistence, responsive layout and no toggle writes passed');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
