const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/**',async route=>{const u=new URL(route.request().url());assert.equal(route.request().method(),'GET','Settings must never write orders');let result={};if(u.pathname.endsWith('/profiles'))result={selected:'paper',verified:true,epoch:'settings-test'};else if(u.pathname.includes('/stock-chart/'))result={con_id:7,generation:'x',symbol:'MNQ',security_type:'FUT',interval:5,session:u.searchParams.get('session'),bars:Array.from({length:80},(_,i)=>({time:1790947800+i*300,open:100,high:102,low:99,close:101}))};else if(u.pathname.includes('/chart-ema/')){requests.push(u.searchParams.get('frames'));result={con_id:7,session:u.searchParams.get('session'),frames:{15:[{time:1790947800,open:100,high:102,low:99,close:101}]}};}else if(u.pathname.includes('/paper-chart/'))result={known:true,enabled:true,active:false,status:'idle',position:0};else if(u.pathname.endsWith('/bootstrap'))result={positions:[]};await route.fulfill({json:result});});
await page.goto('http://127.0.0.1:8765/superchart?con_id=7&session=rth');await page.waitForFunction(()=>document.getElementById('order-status').textContent.includes('Trading'));
await page.locator('#settings').click();const setting=k=>page.locator(`[data-setting="${k}"]`);
assert.equal(await setting('positions').isChecked(),false);assert.equal(await setting('positionUnit').isDisabled(),true);
await setting('positions').check();await setting('positionUnit').selectOption('ticks');await setting('bracketUnit').selectOption('ticks');await setting('executionLabels').check();
await setting('holdingsVisible').uncheck();assert.equal(await setting('profit').isDisabled(),true);await setting('holdingsVisible').check();
await page.getByRole('button',{name:'Indicators',exact:true}).click();await setting('emaLength').fill('30');await setting('emaLength').press('Tab');await setting('emaFrame').selectOption('15');await setting('fvg.minTicks').fill('4');await setting('fvg.minTicks').press('Tab');await setting('previousValues.baseChart').uncheck();
await page.waitForTimeout(2300);assert.ok(requests.some(s=>s.includes('15')&&s.includes('60')&&s.includes('1440')));
const chart=page.frames().find(f=>f.url().includes('/frame'));
assert.equal(await chart.evaluate(()=>displayOptions.emaLength),30);assert.equal(await chart.evaluate(()=>displayOptions.positionUnit),'ticks');assert.equal(await chart.evaluate(()=>displayOptions.fvg.minTicks),4);assert.equal(await chart.evaluate(()=>displayOptions.executionLabels),true);
await page.locator('.template-footer>button').click();await page.getByRole('menuitem',{name:'Save as…',exact:true}).click();await page.locator('.template-save input').fill('Test template');await page.locator('.template-save button[type=submit]').click();await setting('emaLength').fill('40');await setting('emaLength').press('Tab');await page.locator('.template-footer>button').click();await page.getByRole('menuitem',{name:'Test template',exact:true}).click();assert.equal(await setting('emaLength').inputValue(),'30');
for(const width of [1440,393])for(const zh of [false,true])for(const light of [false,true]){await page.setViewportSize({width,height:900});await page.evaluate(({zh,light})=>{document.documentElement.lang=zh?'zh':'en';document.body.classList.toggle('light',light);},{zh,light});await page.getByRole('button',{name:/^(Done|完成)$/}).click();await page.locator('#settings').click();assert.ok(await page.locator('#display').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.screenshot({path:`/tmp/wheel-settings-${width}-${zh}-${light}.png`});}
await page.getByRole('button',{name:/^(Done|完成)$/}).click();await page.reload();await page.waitForFunction(()=>document.getElementById('order-status').textContent.includes('Trading'));await page.locator('#settings').click();assert.equal(await setting('positionUnit').inputValue(),'ticks');assert.equal(await setting('executionLabels').isChecked(),true);assert.deepEqual(errors,[]);console.log('Settings: native defaults, dependencies, chart propagation, MTF requests, templates, reload persistence and responsive themes/languages passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
